### PR TITLE
Update docs to reflect repayment flow

### PR DESCRIPTION
**Pull request by deanrecord**
Before:
Screenshot 2021-02-10 at 17 43 57

After:
Screenshot 2021-02-10 at 17 43 32

Before:
Screenshot 2021-02-10 at 17 44 13

After:
Screenshot 2021-02-10 at 17 43 41

### CODE REVIEW

**Comment by deanrecord** [comment]
Any thoughts on wording here?

**Comment by victokoh** [comment]
> Any thoughts on wording here?

seems really word-y, especially the first sentence.

"[1] The system will record the repayments and wait for a deposit into your receiving account matching the amount and reference you specified when making the API call, **(split here with period)** [2] when the money is deposited the system will automatically distribute the funds to the investors and notify them of a repayment." 

For part [1], mentions an API call - might be better to link to the actual call they'd have had to make to get the amount and reference.

**Comment by victokoh** [comment]
Also that `Repaying the Investment screen` - is it actually the GET call that generates them the reference??

**Comment by deanrecord** [comment]
> Also that `Repaying the Investment screen` - is it actually the GET call that generates them the reference??

It has both the GET and POST

**Pull request merged**
